version: '3'
services:
  cassandra:
    image: cassandra
    hostname: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=ThePassword
      - MYSQL_DATABASE=mysql